import { LayoutDashboard, Video, BarChart3, Settings2, ShieldCheck, Mail, Users, Settings, Palette, Grip, LayoutDashboardIcon, PanelBottom, Landmark, ImagePlus, MessageCircleMore, NotepadText, User2, Layers2 } from "lucide-react";

export const NAV_ITEMS = [
  { icon: LayoutDashboardIcon, label: "Dashboard", href: "/dashboard" },
  { icon: Grip, label: "Services", href: "/services" },
  { icon: PanelBottom, label: "Packages", href: "/packages" },
  { icon: Landmark, label: "Five Pillars of Islam", href: "/fivePillarsOfIslam" },
  { icon: Users, label: "Contacts", href: "/contacts" },
  { icon: ImagePlus, label: "Gallery", href: "/gallery" },
  { icon: MessageCircleMore, label: "Reviews", href: "/reviews" },
  { icon: NotepadText, label: "Blogs", href: "/blogs" },
  { icon: User2, label: "Roles & Permissions", href: "/roles_permissions" },
  { icon: Video, label: "Video News", href: "/video-news" },
  { icon: BarChart3, label: "Advertisement", href: "/advertisement" },
  { icon: LayoutDashboard, label: "Categories", href: "/categories" },
  { icon: Settings2, label: "Sub Categories", href: "/sub-categories" },
  { icon: ShieldCheck, label: "Role Management", href: "/role-management" },
  { icon: Users, label: "Admin Management", href: "/admin-management" },
  { icon: Mail, label: "Contact", href: "/contact" },
  { icon: Users, label: "Reporter", href: "/reporter" },
  { icon: Mail, label: "News Poll", href: "/news-poll" },
  { icon: Settings, label: "General Setting", href: "/general-setting" },
  {
    icon: Settings,
    label: "Page Setting",
    href: "/page-setting",
    children: [
      { label: "Hero area", href: "/dashboard/page-setting/hero-area", icon: Layers2 },
      { label: "About us", href: "/dashboard/page-setting/about-us", icon: NotepadText },
      { label: "Contact us", href: "/dashboard/page-setting/contact-us", icon: Mail },
    ],
  },
  { icon: User2, label: "Update Profile", href: "/update-profile" },
  { icon: Palette, label: "Theme", href: "/theme" },
];
